var recursosInter = {
	CHART_URL : '/produccion/ext-3.2.1/resources/charts.swf',
	advertencia : 'Advertencia',
	agregar : 'Agregar',
	articulo : 'Artículo',
	articulos : 'Artículos',
	autenticacion_exitosa : 'Autenticación exitosa',
	autenticacion_fallo : 'Autenticación falló',
	borrar : 'Borrar',
	buscando : 'Buscando ...',
	busqueda : 'Búsqueda',
	cancelar : 'Cancelar',
	clave : 'Clave',
	cliente : 'Cliente',
	conectantose : 'Conectándose',
	confirmar : 'Confirmar',
	detalle_corchetes: '[Detalle]',
	enviando_datos : 'Enviando datos',
	estatus : 'Estatus',
	fecha : 'Fecha',
	fechaDesde : 'Fecha desde',
	fechaHasta : 'Fecha hasta',
	login : 'Conectarse',
	modificar : 'Modificar',
	nombre_usuario : 'Usuario',
	nro_pedido : 'Nº pedido',
	ordenes_produccion_cabecera: 'Órdenes de producción [Cabecera]',
	ordenes_terminacion_cabecera: 'Órdenes de terminación [Cabecera]',
	produccion_pulido_cabecera: 'Producción de pulido [Cabecera]',
	produccion_prensa_cabecera: 'Producción de prensas [Cabecera]',
	piezaGenerica : 'Tipo de pieza',
	por_favor_ingrese : 'Por favor ingrese',
	precio : 'Precio',
	produccion_chapa_cabecera : 'Producción de chapa [Cabecera]',
	proveedor : 'Proveedor',
	recepciones_cabecera : 'Remitos recibidos [cabecera]',
	referencia : 'Referencia',
	servidor_de_autenticacion_inaccesible : 'Servidor de autenticación inaccesible',
	unidad : 'Unidad',
	usuario_o_clave_invalidos : 'Usuario o clave inválidos'

};